name: pull_request

permissions:
  checks: write
  pull-requests: write

on:
  pull_request:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get the code
        uses: actions/checkout@v4
      - name: package
        run: mvn clean package
      - name: publish the test result
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "**/target/surefire-reports/**/*.xml"   
          comment_mode: always     
